language: node_js
node_js:
- node
sudo: false
install: yarn install
script:
- echo "skipping tests"
deploy:
  provider: heroku
  api_key:
    secure: "dwIVoNPyDMw1vPEDbbhqvLbaYzwJTmCdKUaAQpinMbTtQR6CRRsGtgcMQeD3BbUHLb6hXOY1OTZJuM22In9q4CC96AhCJwue1TdpqrU14EZZaxdnIpLtcs52EKUk8YlM3gfBd21b/LvnG8qF2ryZEBBWj4E362eUZd+igO+DEZ8Q8VapqMPpyOG61VdYKaXsDLTHbIq6cbUD0Q5/SDCTa9gNyBCeyolDcPhxwmLkuEACbfOoTNKAkqqZm4g3eJ4bDbYGUIpHSLbmUt5v29yMBmy5cnI1fX0YlZPj98/yKvFCIxlF/kTfnoJNZBnzY7tlg6xrkfC2wWmH26yKYhn9cxMkrLlUCJqFNYXECu4uC10mE0xQ+VwZysMtAIhfQBkuA48/TdoezJ9qsFP1Ch2aKcAoCFxDHcwDMu1el/FlITaJNa5sRJvjrwUgRdblUTa2gIi5AFPSBb+hS9U7/zdkaivQ9plvViC5vhwt4eyfI1nBuFLZt8G2zd6nklG0r6T36BvDyrpUZaQqLugtYgsADejjjwhXe/yq7H6vzY8aS6XDMn4KWgGmsX66bmAbsRQC9ebZzcdyxZ5RsqIEnVxpIJWyW9OwpS7I+McMrq969PjqRMWE9sWu2z3s7E7sgh4MUpjtO3JKaa6RW8O9RxgZ3S4CDYiK+9jzh5bHpcX0qA0="
  app: node-express-postgre
  on:
    repo: alpersonalwebsite/node-express-postgre